services:
  skeleton:
    container_name: skeleton_nginx
    image: skkzsh/nginx
    build: .
    ports:
      - 10080:80
    environment:
      TZ: Asia/Tokyo
    healthcheck:
      test: curl -f http://localhost/health || exit 1
      interval: 10s
      timeout: 3s
      retries: 2
      start_period: 5s
